### ISSUE TITLE
Hypervolume value

### ISSUE THREAD

**Issue by eniocc** [infinito84/pareto-hypervolume#1]
Hi Sir.
First: thank your for your job, it is simple and beautiful.
Second: What is the reference points used? Sometimes my Hypervolume is negative. Why thist?

Thank you again =)

**Comment by infinito84** [comment]
Hi thanks!,

Check this file: https://github.com/infinito84/pareto-hypervolume/blob/master/js/hyperVolume.js
I have two implementations of hypervolume calculation, one was given by my professor.
Both implementations work for minimization problems, maybe you are maximizing.

**Comment by eniocc** [comment]
Thanks for the quickly reply.
I am work with minimization problems.
May you test this points please?

592.086 22 
628.065 19
624.991 20 
601.262 21 

For this points, my hypervolume is 0 (zero). I don't understad why.

**Comment by infinito84** [comment]
You can test here (create a file and use TAB as separator):
https://infinito84.github.io/pareto-hypervolume/
After you load the file change the nadir point to: 630, 23 respectively
then the hypervolume gives: 9.97.

**Comment by eniocc** [comment]
I understood you point.
When I used your references points * 630, 23* the hypervolume is 9.97 it's true.
But, Why we are not using NADIR points (**628.065 19**)?

**Comment by infinito84** [comment]
I really got focused in the pareto's frontier for implementing NSGA II algorithm, but I don't an expert in the hypervolume metric, if you can share the theory and the explanation I thank you!

**Comment by eniocc** [comment]
Hypervolume is a metric used to calculate the performance of a multiobjective algorithm. It calculates at the same time how good the spreading at the pareto border is and how close the border is to the ideal point (opposite the NADIR point).

I found that when we have only 2 points on the pareto border, the NADIR point is formed by the highest value of both points, that is, (Xmax, Ymax). That said, the hypervolume will be zero because it will not be possible to calculate an area. The strategy for calculating the hypervolume of a border with only 2 points is to use arbitrary points so that (Xi, Yi) is greater than (Xmax, Ymax) of the Pareto frontier, ie Xi> Xmax and Yi> Ymax.

This strategy is exactly what you did. Instead of using (628.065, 19) you used points much larger than the NADIR point, solving the problem of hypervolume calculation for problems of only 2 points at the border.

In addition, if a frontier is only 2 points, it is likely that it is not a problem of impasse but of another type.

Really thanks for this debate Sir.
I really appreciate this good conversation.

If you want, you can close this issue.

**Comment by infinito84** [comment]
Thanks for your explanation very helpful.
